language: node_js

node_js:
    - "4.2.1"

sudo: false

# We need to check out cognicity-reports as the parent folder of this data source, so that the references to the base object will work.
# We do this here as a custom 'before_install' script which Travis will execute.
# If cognicity-reports has a branch with the same name as ours, use that. Otherwise use the master branch on cognicity-reports.
# Make sure we're in the right location at the end - i.e. this data source's source folder - as this is where the build and test will occur. 

before_install:
    - export BASE_BRANCH=master
    - if ( git ls-remote --exit-code https://github.com/smart-facility/cognicity-reports.git $TRAVIS_BRANCH ); then export BASE_BRANCH=$TRAVIS_BRANCH; fi
    - echo "BASE_BRANCH=$BASE_BRANCH"
    - git clone --depth=50 --branch=$BASE_BRANCH https://github.com/smart-facility/cognicity-reports.git smart-facility/cognicity-reports
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/smart-facility/cognicity-reports-powertrack.git smart-facility/cognicity-reports/gnip-powertrack
    - cd smart-facility/cognicity-reports
    - npm install
    - cd gnip-powertrack
